name: release-please

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - name: release-please-action
  # You may pin to the exact commit or the version.
  # uses: google-github-actions/release-please-action@f0145e31b50c56905571d69a63bbe997c0ce6dd1
      uses: google-github-actions/release-please-action@v3.1.2
      with:
        command: manifest # optional, default is
